# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn

      - name: Generating static files
        run: yarn build
      - name: Exporting static files
        run: yarn export

      - name: Deploying to gh-pages
        run: |
          git config --local user.name osbuktp
          git config --local user.email os.buktp@yandex.ru
          git remote set-url origin https://github.com/${GITHUB_REPOSITORY}
          git add .
          git commit -am "Build ${GITHUB_RUN_ID}"
          git push -f origin gh-pages
        working-directory: ./out
